name: Characters and Locations
author: johnysandels & ryankhart
disabled: false
description: Corrections for various characters' and locations' names. System lexicon for any system backend specific mispronunciations.
files:
  - lexicon.pls
