name: Americanize UK voice word pronunciations
author: ryankhart
disabled: false
description: An opinionated lexicon for those using UK voices but prefer the US pronunciation for words such as "lieutenant". For example, this forces even UK voices to say "Loo-ten-ant" rather than "Left-ten-ant".
files:
  - lexicon.pls
