name: Characters Locations Polly
author: johnysandels
disabled: false
description: Corrections for various characters' and locations' names. Amazon Polly version for any polly specific backend bugs.
files:
  - lexicon.pls
