name: Characters and Locations Polly
author: johnysandels & ryankhart
disabled: false
description: Corrections for various characters' and locations' names. Amazon Polly version for any Amazon Polly backend specific mispronunciations.
files:
  - lexicon.pls
